[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py310"  # Замените на вашу версию Python

# Включение наборов правил
select = ["E", "F", "I", "UP", "B", "SIM", "C4", "RUF"]

# Отключение конкретных правил (если нужно)
ignore = ["E501"]  # Например, игнорировать превышение длины строки

# Папки и файлы для исключения
exclude = [
    ".venv",
    "build",
    "dist",
    "__pycache__",
    "migrations"
]

# Автоисправление при запуске (если используешь через CLI)
fix = true
